{
    "openapi": "3.0.0",
    "info": {
        "description": "API aplicação da AncarX.",
        "version": "1.0.0",
        "title": "Swagger IronLinux",
        "license": {
            "name": "IronLinux",
            "url": "https://ironlinux.com.br/"
        }
    },
    "servers": [
        {
            "url": "http://localhost:3333/v1",
            "description": "API Local"
        }
    ],
    "tags": [
        {
            "name": "HomePage",
            "description": "Todos os endpoints da página inicial da aplicação"
        },
        {
            "name": "User",
            "description": "Todos os endpoints de usuários da aplicação"
        },
        {
            "name": "Authenticate",
            "description": "Todos os endpoint de autenticação da aplicação"
        }
    ],
    "paths": {
        "/user/{id}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Listar as informações de um usuário específico",
                "description": "Listar as informações de um usuário específico",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "$ref": "#/components/responses/User"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            },
            "put": {
                "tags": [
                    "User"
                ],
                "summary": "Atualizar um usuário",
                "description": "Atualizar um usuário",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/User"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            },
            "delete": {
                "tags": [
                    "User"
                ],
                "summary": "Deletar um usuário",
                "description": "Deletar um usuário",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            },
            "patch": {
                "tags": [
                    "User"
                ],
                "summary": "Inativar um usuário",
                "description": "Inativar um usuário",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/User"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            }
        },
        "/authenticate": {
            "post": {
                "tags": [
                    "Authenticate"
                ],
                "summary": "Autenticar o usuário da aplicação",
                "description": "Autenticar o usuário da aplicação",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Authenticate"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "$ref": "#/components/responses/Authenticated-Successful"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Listar as informações de todos os usuário da aplicação",
                "description": "Listar as informações de todos os usuário da aplicação",
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/ArrayOfUser"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Criar um novo usuário",
                "description": "Criar um novo usuário",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "$ref": "#/components/responses/User"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            }
        },
        "/home_page": {
            "get": {
                "tags": [
                    "HomePage"
                ],
                "summary": "Listar informações da página inicial",
                "description": "Listar informações da página inicial",
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/HomePage"
                    }
                }
            },
            "post": {
                "tags": [
                    "HomePage"
                ],
                "summary": "Criar/Atualizar as informações da página inicial",
                "description": "Criar/Atualizar as informações da página inicial",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/HomePage"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "$ref": "#/components/responses/HomePage"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            }
        },
        "/rating/{id}": {
            "delete": {
                "tags": [
                    "Rating"
                ],
                "summary": "Deletar uma avaliação",
                "description": "Deletar uma avaliação",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id da avaliação",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            }
        },
        "/rating": {
            "get": {
                "tags": [
                    "Rating"
                ],
                "summary": "Buscar avaliações dos Cursos",
                "description": "Buscar avaliações dos Cursos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "ratings": [
                                        {
                                            "id": 2,
                                            "rantingName": "teste",
                                            "name": "a",
                                            "office": "teste",
                                            "imageURL": "teste",
                                            "position": 1,
                                            "description": "teste",
                                            "starts": 4.5,
                                            "createdAt": "2021-09-06T01:26:16.687Z",
                                            "updatedAt": "2021-09-06T01:26:16.688Z",
                                            "page": "HOMEPAGE"
                                        },
                                        {
                                            "id": 3,
                                            "rantingName": "teste",
                                            "name": "a",
                                            "office": "teste",
                                            "imageURL": "teste",
                                            "position": 1,
                                            "description": "teste",
                                            "starts": 4.5,
                                            "createdAt": "2021-09-11T00:27:46.743Z",
                                            "updatedAt": "2021-09-11T00:27:46.744Z",
                                            "page": "HOMEPAGE"
                                        },
                                        {
                                            "id": 4,
                                            "rantingName": "teste",
                                            "name": "a",
                                            "office": "teste",
                                            "imageURL": "teste",
                                            "position": 1,
                                            "description": "teste",
                                            "starts": 4.5,
                                            "createdAt": "2021-09-11T00:28:05.660Z",
                                            "updatedAt": "2021-09-11T00:28:05.660Z",
                                            "page": "HOMEPAGE"
                                        }
                                    ],
                                    "totalPages": 1,
                                    "totalRecords": 3,
                                    "currentPage": 1
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Rating"
                ],
                "summary": "Criar Avaliação dos Cursos",
                "description": "Criar Avaliação dos Cursos",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "rantingName": "avaliacoes_principais",
                                    "name": "Lucas",
                                    "office": "CEO",
                                    "imageBase64": "SFDSFD651SFD651SFDS65FD1FS6D51SFD61FSD651SFF6D51FS6.6a1.s4af651gg.fds4sa64.sgd4.fdg",
                                    "position": 1,
                                    "description": "Muito legal o curso, sensacional",
                                    "starts": 4.5
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "$ref": "#/components/responses/Rating"
                    },
                    "401": {
                        "$ref": "#/components/responses/401"
                    },
                    "500": {
                        "$ref": "#/components/responses/500"
                    }
                }
            }
        }
    },
    "components": {
        "examples": {
            "UserWithoutID": {
                "value": {
                    "id": "LNQT8FFFo0Qgy33Ca6E5NmQia8P2",
                    "name": "Usuário de Exemplo",
                    "email": "email@teste.com.br",
                    "status": "active",
                    "accesspanel": true,
                    "fcmToken": "eF1fPaI8SUmMKLrqOrqKLA:APA91bHyh5GJQLrpJ6TVBNng4EitgVZtIsRnvDoVdzk9DUqBU9t6qybtKYR8t5_AHNWx_9_GkBDTw4h8T5XWzXMmJqsiKyRwtU8zcRIakM9",
                    "storeId": "0011I00000KMbGzQAL",
                    "role": "Manager",
                    "shoppingCode": "SNA",
                    "shoppingCodeList": [
                        "SNA",
                        "SNE"
                    ]
                }
            },
            "UserWithID": {
                "value": {
                    "id": "LNQT8FFFo0Qgy33Ca6E5NmQia8P2",
                    "name": "Usuário de Exemplo",
                    "email": "email@teste.com.br",
                    "fcmToken": "eF1fPaI8SUmMKLrqOrqKLA:APA91bHyh5GJQLrpJ6TVBNng4EitgVZtIsRnvDoVdzk9DUqBU9t6qybtKYR8t5_AHNWx_9_GkBDTw4h8T5XWzXMmJqsiKyRwtU8zcRIakM9",
                    "storeId": "0011I00000KMbGzQAL",
                    "role": "Manager",
                    "shoppingCode": "SNA"
                }
            },
            "UserResponseList": {
                "value": [
                    {
                        "id": "LNQT8FFFo0Qgy33Ca6E5NmQia8P2",
                        "name": "Usuário de Exemplo",
                        "status": "active",
                        "accesspanel": true,
                        "fcmToken": "eF1fPaI8SUmMKLrqOrqKLA:APA91bHyh5GJQLrpJ6TVBNng4EitgVZtIsRnvDoVdzk9DUqBU9t6qybtKYR8t5_AHNWx_9_GkBDTw4h8T5XWzXMmJqsiKyRwtU8zcRIakM9",
                        "storeId": "0011I00000KMbGzQAL",
                        "role": "Manager",
                        "shoppingCode": "SNA",
                        "shoppingCodeList": [
                            "SNA",
                            "SNE"
                        ]
                    },
                    {
                        "id": "LNQT8FFFo0Qgy33Ca6E5NmQia8P2",
                        "name": "Usuário de Exemplo",
                        "status": "active",
                        "accesspanel": true,
                        "fcmToken": "eF1fPaI8SUmMKLrqOrqKLA:APA91bHyh5GJQLrpJ6TVBNng4EitgVZtIsRnvDoVdzk9DUqBU9t6qybtKYR8t5_AHNWx_9_GkBDTw4h8T5XWzXMmJqsiKyRwtU8zcRIakM9",
                        "storeId": "0011I00000KMbGzQAL",
                        "role": "Manager",
                        "shoppingCode": "SNA",
                        "shoppingCodeList": [
                            "SNA",
                            "SNE"
                        ]
                    }
                ]
            }
        },
        "securitySchemes": {
            "JWT_Token": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            }
        },
        "responses": {
            "Rating": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "rating": {
                                "value": {
                                    "id": 4,
                                    "rantingName": "avaliacoes_principais",
                                    "name": "Lucas",
                                    "office": "CEO",
                                    "imageURL": "https://localhost:3000/images/image.png",
                                    "position": 1,
                                    "description": "Muito legal o curso, sensacional",
                                    "starts": 4.5,
                                    "createdAt": "2021-09-11T00:28:05.660Z",
                                    "updatedAt": "2021-09-11T00:28:05.660Z",
                                    "page": "HOMEPAGE"
                                }
                            }
                        }
                    }
                }
            },
            "Authenticated-Successful": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "Authenticated-Successful": {
                                "value": {
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmZpZ3VlaXJlZG9AZ21haWwuY29tIiwiaWF0IjoxNjMwODYyNzk0LCJleHAiOjE2MzA5NDkxOTQsInN1YiI6IjEifQ.E6UvrVpXbqPGV9ec6ButjBKCcIyNN6UraYTl58dOLrc",
                                    "expiresIn": "2021-09-11 19:00:00"
                                }
                            }
                        }
                    }
                }
            },
            "User": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "user-info": {
                                "value": {
                                    "id": 1,
                                    "name": "Daniel",
                                    "description": "Sou um cara muito legal",
                                    "email": "devfigueiredo@gmail.com",
                                    "active": false
                                }
                            }
                        }
                    }
                }
            },
            "ArrayOfUser": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "user-info": {
                                "value": [
                                    {
                                        "id": 1,
                                        "name": "Daniel",
                                        "description": "Sou um cara muito legal",
                                        "email": "devfigueiredo@gmail.com",
                                        "active": false
                                    },
                                    {
                                        "id": 1,
                                        "name": "Daniel",
                                        "description": "Sou um cara muito legal",
                                        "email": "devfigueiredo@gmail.com",
                                        "active": false
                                    }
                                ]
                            }
                        }
                    }
                }
            },
            "HomePage": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "user-info": {
                                "value": {
                                    "infoHomePage": {
                                        "id": 1,
                                        "title": "Quer aprender mais sobre o mundo de Linux e Segurança ?",
                                        "description": "IronLinux presta serviços de treinamento e consultoria nas principais áreas de segurança e sistemas operacionais. Descubra mais entrando em contato conosco.",
                                        "imageURL": "",
                                        "titleHomePageSpecialties": "Uma ampla diversidades de aprendizados",
                                        "titleHomePageCourses": "Cursos Disponíveis",
                                        "titleHomePagePosts": "Últimos posts do blog:",
                                        "titleHomePageExperts": "Precisa de um especialista?",
                                        "descriptionHomePageExperts": "Você precisa de alguma ajuda com:Linux, Segurança, Servidores ou Roteadores?",
                                        "titleContactUS": "Fale Conosco",
                                        "page": "HOMEPAGE"
                                    },
                                    "aboutCourses": {
                                        "id": 1,
                                        "titleFirst": "Conheça as variedades da IronLinux",
                                        "title1": "Uma ampla seleção de cursos",
                                        "description1": "Somos especialistas em implementar soluções com software open source e depois mostrar para o cliente como realizar a utilização das mesas..",
                                        "title2": "Aprenda Sem Limites",
                                        "description2": "Desenvolva habilidades com cursos, certificados e graduações on-line.",
                                        "title3": "Prepare-se para uma carreira",
                                        "description3": "Em áreas de alta demanda, como TI, IA e engenharia de nuvem, exige conhecimentos em Segurança de Informação",
                                        "title4": "Tenha um histórico reconhecido pelo setor",
                                        "description4": "Demonstre suas novas habilidades compartilhando o certificado do curso, certificado profissional e afins...",
                                        "imageURL": "teste.png",
                                        "createdAt": "2021-09-05T02:11:51.802Z",
                                        "updatedAt": "2021-09-04T00:00:00.000Z",
                                        "page": "HOMEPAGE"
                                    },
                                    "aboutConsulting": {
                                        "id": 1,
                                        "titleFirst": "Não deixe para amanhã, o que se pode ter hoje.",
                                        "title": "Certificação Expert",
                                        "description": "Nossa plataforma de cursos possuem funções que auxiliam o aluno no processo de ensino e aprendizagem, possibilitando o emprego prático dos conhecimentos adquiridos!",
                                        "checkedDescription1": "Alto Nivel de Conhecimento e Aprendizado",
                                        "checkedDescription2": "Você apredenderá os niveis mais baixos das regras padrões de segurança da informação",
                                        "checkedDescription3": "Qualidade e experiência em treinamentos imersivos e práticos.",
                                        "imageURL": "tete.png",
                                        "createdAt": "2021-09-05T02:10:27.398Z",
                                        "updatedAt": "2021-09-04T00:00:00.000Z",
                                        "page": "HOMEPAGE"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "401": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "unauthorized": {
                                "value": {
                                    "error": "Unable to authenticate user. Please try to login again!"
                                }
                            },
                            "incorret-email-password": {
                                "value": {
                                    "error": "Email/Password incorret!"
                                }
                            }
                        }
                    }
                }
            },
            "400": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "failed-email-already-exists": {
                                "value": {
                                    "error": "User Already Exists"
                                }
                            }
                        }
                    }
                }
            },
            "500": {
                "description": "",
                "content": {
                    "application/json": {
                        "examples": {
                            "failed-token": {
                                "value": {
                                    "error": "Error validating access permissions!"
                                }
                            }
                        }
                    }
                }
            }
        },
        "schemas": {
            "Authenticate": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "Rating": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "rantingName": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "office": {
                        "type": "string"
                    },
                    "imageURL": {
                        "type": "string"
                    },
                    "position": {
                        "type": "number"
                    },
                    "description": {
                        "type": "string"
                    },
                    "starts": {
                        "type": "number"
                    }
                }
            },
            "User": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "active": {
                        "type": "boolean"
                    }
                }
            },
            "HomePage": {
                "type": "object",
                "properties": {
                    "infoHomePage": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "number"
                            },
                            "title": {
                                "type": "string"
                            },
                            "description": {
                                "type": "string"
                            },
                            "imageURL": {
                                "type": "string"
                            },
                            "titleHomePageSpecialties": {
                                "type": "string"
                            },
                            "titleHomePageCourses": {
                                "type": "string"
                            },
                            "titleHomePagePosts": {
                                "type": "string"
                            },
                            "titleHomePageExperts": {
                                "type": "string"
                            },
                            "descriptionHomePageExperts": {
                                "type": "string"
                            },
                            "titleContactUS": {
                                "type": "string"
                            },
                            "page": {
                                "type": "string"
                            }
                        }
                    },
                    "aboutCourses": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "number"
                            },
                            "titleFirst": {
                                "type": "string"
                            },
                            "title1": {
                                "type": "string"
                            },
                            "description1": {
                                "type": "string"
                            },
                            "title2": {
                                "type": "string"
                            },
                            "description2": {
                                "type": "string"
                            },
                            "title3": {
                                "type": "string"
                            },
                            "description3": {
                                "type": "string"
                            },
                            "title4": {
                                "type": "string"
                            },
                            "description4": {
                                "type": "string"
                            },
                            "imageURL": {
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "string"
                            },
                            "updatedAt": {
                                "type": "string"
                            },
                            "page": {
                                "type": "string"
                            }
                        }
                    },
                    "aboutConsulting": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "number"
                            },
                            "titleFirst": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            },
                            "description": {
                                "type": "string"
                            },
                            "checkedDescription1": {
                                "type": "string"
                            },
                            "checkedDescription2": {
                                "type": "string"
                            },
                            "checkedDescription3": {
                                "type": "string"
                            },
                            "imageURL": {
                                "type": "string"
                            },
                            "createdAt": {
                                "type": "string"
                            },
                            "updatedAt": {
                                "type": "string"
                            },
                            "page": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "security": [
        {
            "JWT_Token": []
        }
    ]
}